services:
  python-ci-cd-app:
    build:
      context: .
      args:
        - BUILD_ENVIRONMENT=development
    environment:
      APP_ENV: development
    command: [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    ports:
      - "5051:8000"
    user: appuser
    volumes:
      - ./src:/home/appuser/src
      - ./public:/home/appuser/public

    # [Interactive Shell] Can be Used For Debugging Docker Scripts
    stdin_open: true # docker run -i
    tty: true        # docker run -t
