services:
  fastship-app:
    image: fastship-app:development
    build:
      context: ..
      args:
        BUILD_ENVIRONMENT: development
    environment:
      APP_ENV: development
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "5051:8000"
    user: appuser
    volumes:
      - ../src:/home/appuser/src
      - ../public:/home/appuser/public
      - ../uploads:/home/appuser/uploads
    stdin_open: true
    tty: true
