apiVersion: v1
kind: ConfigMap
metadata:
  name: python-cicd-api-config
  labels:
    app.kubernetes.io/name: python-cicd
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: api
data:
  APP_ENV: production
