apiVersion: v1
kind: ConfigMap
metadata:
  name: fastship-app-api-config
  labels:
    app.kubernetes.io/name: fastship-app
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: api
data:
  APP_ENV: production
