apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastship-app-uploads-nfs
  labels:
    app.kubernetes.io/name: fastship-app
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: api
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.50.10
    path: /srv/nfs/fastship-app-uploads
