apiVersion: v1
kind: Service
metadata:
  name: fastship-app-api-service
  labels:
    app.kubernetes.io/name: fastship-app
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fastship-app
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
