apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: python-cicd
  labels:
    app.kubernetes.io/name: python-cicd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: python-cicd
