apiVersion: v1
kind: Service
metadata:
  name: python-cicd
  labels:
    app.kubernetes.io/name: python-cicd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: python-cicd
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
