# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python App Docker Build

on:
  push:
    branches:
      - github-actions-cd-docker

    # ignore pull request events to paths matching **.md and .github/workflows/*yml
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
      - name: Install Project Dependencies
        run: poetry install --no-interaction --no-root
      - name: Run Tests
        run: poetry run pytest -v


  build_deploy_docker_container:
    name: Build Docker Container, Push to Docker hub & Deploy to the Staging Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        env:
          DOCKER_REPO: rezwanul7/python-cicd
        run: |
          docker buildx create --use
          docker buildx build \
            --file Dockerfile \
            --tag $DOCKER_REPO:latest \
            --push .

      - name: Copy files via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "common.yaml, compose.stag.yaml, deploy.sh"
          target: ~/PythonCICD/

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/PythonCICD
            bash deploy.sh
