apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: python-cicd-staging

resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml

patches:
  - path: config-map-patch.yaml

images:
  - name: rezwanul7/python-cicd
    newTag: sha-replace-with-full-git-sha
